### ISSUE TITLE
Generate accelerator wrapper without a CSR manager

### ISSUE THREAD

**Issue by RickLuiken** [KULeuven-MICAS/snax_cluster#190]
I would like to generate an accelerator wrapper without a CSR manager, as the accelerator handles the CSRs itself. To do this, the CSR control ports should be routed into the accelerator instead of the CSR manager. I tried setting the `snax_num_rw_csr` and `snax_num_ro_csr` to zero, however, this gives compile errors in the CSR manager.

While generating the template, there are two options to provide this bypass:
1. Detect when the `snax_num_*_csr` values are both zero.
2. Add a new config option (something like `snax_csr_manager_disable`)

Let me know what you think, I can provide a PR if you agree on one of the options!

**Comment by rgantonio** [comment]
Hi @RickLuiken!

Let's do the `snax_csr_manager_disable` option 😄 at least that's explicitly clear in the configuration naming, rather than just putting everything to 0.

I would appreciate if you do the PR! Sorry if we will reply late. Some of us maintainers are on vacation but we'll look at them when we have the time to!

Arigathanks!!!

- Ry 🦇
