### ISSUE TITLE
Axi dependency is using v0.39.4 instead of v0.39.1

### ISSUE THREAD

**Issue by RickLuiken** [KULeuven-MICAS/snax_cluster#221]
Hi!

As you know, for the CONVOLVE tapeout we are using axi v0.39.1. However, I noticed that currently bender is using v0.39.4. This is due to the way bender works: it uses the [same versioning as cargo from the rust language](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html). Currently, there is Bender.yml which specifies 0.39.1, and there is Bender.local which specifies 0.39.0 (both of which will fetch axi v0.39.4).

I suggest we get rid of the Bender.local file and use the following in the Bender.yml file:
`axi: {git: https://github.com/pulp-platform/axi.git, version: =0.39.1}`
which will set the axi version to 0.39.1 (notice the = sign)

**Comment by rgantonio** [comment]
@RickLuiken OK! Good catch! Will do your request 😄

**Comment by rgantonio** [comment]
Solving with PR #223. @RickLuiken I placed the `=` sign inside the `Bender.local` instead otherwise the Bender prompts:

![image](https://github.com/user-attachments/assets/2eedf296-44f3-4907-b0b2-029114c0318e)

When inside the `Bender.local` it overrides all the prompts. I double-checked the `Bender.lock` and it does show it uses 0.39.1 now 😃 

Let me know what you think. Thanks!

**Comment by rgantonio** [comment]
PR #223 fixes this!
