### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by jjl1075337132** [KULeuven-MICAS/snax_cluster#381]
I've encountered a new issue where my program is throwing a segmentation fault when I integrate 12 cores. I'm curious if there's a limit to the number of cores supported by the software for a single cluster. Your guidance would be greatly appreciated, and I look forward to your reply.
![image](https://github.com/user-attachments/assets/082f91d2-4a93-4999-962e-dd7204f95258)

**Comment by rgantonio** [comment]
Hi @jjl1075337132 

Unfortunately, we never really tested for more than 9 cores so far. The original Snitch cluster used 9 (1 for DMA + 8 compute cores). Moreover, we don't really extend to more than 4 cores for now since the number of connections to the memory starts to increase as well.

You have to (1) increase the memory and number of banks, and (2) increase the instruction cache size too.

However, based on the log, what you could do is indeed increase the instruction cache and see if that does something.

https://github.com/KULeuven-MICAS/snax_cluster/blob/c2e597f4a649dbcc738d2a5c9bc2c8d0378a8f60/target/snitch_cluster/cfg/snax_alu.hjson#L75-L79

Probably try to bump it up to 16kB to see if it works.

Let us know if something happens with this.

**Comment by jjl1075337132** [comment]
![image](https://github.com/user-attachments/assets/004a21f4-454d-4578-b128-08b489512adb)
It's still a segmentation fault, and I've also observed that in this architecture, adding more accelerators means more parallel port connections to the interconnect. So, this cluster is probably not well-suited for integrating a multi-core architecture, right?

**Comment by rgantonio** [comment]
Hi @jjl1075337132 

How unfortunate. We shall try on our side but we're not sure if he have the bandwidth to fix this now since we're all working on a project.


>So, this cluster is probably not well-suited for integrating a multi-core architecture, right?

This is a good question. 

The compute cluster was meant to be a multi-accelerator cluster. The entire cluster itself is like "one compute core" essentially.

There are many who confuse that our system is a multi-core architecture, but technically it is more like a "multi-sub-core" architecture packed into one compute cluster. But the entire compute cluster itself is can be treated like one big core.

This cluster is just the "base" computing core but not necessarily a whole big multi-core connecting through the network.

Our architecture has an AXI network that is meant to expand into a multi-core (or multi-compute cluster) architecture. That's where it becomes to become like a "multi-core" system.

I hope this makes sense!

But absolutely the parallel connections are the price to pay for higher bandwidth. There is a trade-off between having to pay so much bandwidth and the area it consumes.

**Comment by jjl1075337132** [comment]
Thank you for your reply, I now have a deeper understanding of this project.

**Comment by rgantonio** [comment]
@jjl1075337132 

If you are interested in going for a more scalable system, we have the extended part in here:

https://github.com/KULeuven-MICAS/HeMAiA

Take note though, just like this SNAX project, everything is still a work in progress 😄 

Again, thanks for your interest in our work!

I will close this issue now.
